services:
  - type: web
    name: finance-agent
    runtime: python
    # 1) install dependencies, 2) pre‑download the HF model
    buildCommand: |
      pip install -r requirements.txt
      python - <<EOF
from transformers import AutoModelForCausalLM
AutoModelForCausalLM.from_pretrained("microsoft/phi-4")
EOF
    # how to start your FastAPI/Uvicorn server
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
