name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # Expose both HF_HUB_TOKEN and DEEPINFRA_API_KEY
    env:
      HF_HUB_TOKEN:       ${{ secrets.HF_HUB_TOKEN }}
      DEEPINFRA_API_KEY:  ${{ secrets.DEEPINFRA_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt